print('Esta aula resolve o >>>DESAFIO 04 - Dissecando uma variável. <<<')
algo = input('Digite algo para mostrarmos seu tipo primitivo e demais informações: >>> ')
print('Você digitou {} e o tipo deste dado é {} '.format(algo, type(algo)))
print('Só tem espaços? {}'.format(algo.isspace()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('Está em maiúscula? {}'.format(algo.isupper()))
print('Está em minúscula ? {}'.format(algo.islower()))
print('Está capitalizada ? {}'.format(algo.istitle()))

